# Generated by Django 4.1.4 on 2023-02-21 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("pt", "Portuguese"),
                            ("other", "Other"),
                            ("unknown", "Unknown/Unreported"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown/Unreported"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("U", "Unknown/Unreported"),
                            ("White", "White"),
                            ("Black or African American", "Black or African American"),
                            ("Asian", "Asian"),
                            (
                                "American Indian or Alaska Native",
                                "American Indian or Alaska Native",
                            ),
                            (
                                "Native Hawaiian or Other Pacific Islander",
                                "Native Hawaiian or Other Pacific Islander",
                            ),
                            ("Hispanic or Latino", "Hispanic or Latino"),
                            ("Other", "Other"),
                        ],
                        default="U",
                        max_length=50,
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("U", "Unknown/Unreported"),
                            ("Elementary school", "Elementary school"),
                            ("Middle school", "Middle school"),
                            (
                                "High school diploma or equivalent",
                                "High school diploma or equivalent",
                            ),
                            ("Some college, no degree", "Some college, no degree"),
                            ("Associate degree", "Associate degree"),
                            ("Bachelor’s degree", "Bachelor’s degree"),
                            (
                                "Graduate or professional degree",
                                "Graduate or professional degree",
                            ),
                        ],
                        default="U",
                        max_length=50,
                    ),
                ),
                (
                    "reading_fluency",
                    models.CharField(
                        choices=[
                            ("U", "Unknown/Unreported"),
                            ("Below basic", "Below basic"),
                            ("Basic", "Basic"),
                            ("Intermediate", "Intermediate"),
                            ("Proficient", "Proficient"),
                        ],
                        default="U",
                        max_length=50,
                    ),
                ),
                (
                    "first_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("pt", "Portuguese"),
                            ("other", "Other"),
                            ("unknown", "Unknown/Unreported"),
                        ],
                        default="Unknown/Unreported",
                        max_length=50,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(default="Unknown/Unreported", max_length=50),
                ),
                (
                    "income",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("U", "Unknown/Unreported"),
                        ],
                        default="Unknown/Unreported",
                        max_length=50,
                    ),
                ),
                ("medical_history", models.TextField(default="Unknown/Unreported")),
                ("medication_use", models.TextField(default="Unknown/Unreported")),
                ("drug_history", models.TextField(default="Unknown/Unreported")),
                ("alcohol_history", models.TextField(default="Unknown/Unreported")),
                ("covid", models.BooleanField(default=False)),
                ("covid_times", models.IntegerField(default=0)),
                (
                    "participant_group",
                    models.CharField(
                        choices=[
                            ("C", "Control"),
                            ("P", "Clinical"),
                            ("O", "Other"),
                            ("U", "Unknown/Unreported"),
                        ],
                        default="Unknown/Unreported",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordsLearningSubtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stone1", models.BooleanField(default=False)),
                ("ear1", models.BooleanField(default=False)),
                ("neck1", models.BooleanField(default=False)),
                ("cloud1", models.BooleanField(default=False)),
                ("foot1", models.BooleanField(default=False)),
                ("seed1", models.BooleanField(default=False)),
                ("tongue1", models.BooleanField(default=False)),
                ("sand1", models.BooleanField(default=False)),
                ("fire1", models.BooleanField(default=False)),
                ("nose1", models.BooleanField(default=False)),
                ("tree1", models.BooleanField(default=False)),
                ("hand1", models.BooleanField(default=False)),
                ("wind1", models.BooleanField(default=False)),
                ("knee1", models.BooleanField(default=False)),
                ("WL_trial1_score", models.IntegerField(default=0)),
                ("stone2", models.BooleanField(default=False)),
                ("ear2", models.BooleanField(default=False)),
                ("neck2", models.BooleanField(default=False)),
                ("cloud2", models.BooleanField(default=False)),
                ("foot2", models.BooleanField(default=False)),
                ("seed2", models.BooleanField(default=False)),
                ("tongue2", models.BooleanField(default=False)),
                ("sand2", models.BooleanField(default=False)),
                ("fire2", models.BooleanField(default=False)),
                ("nose2", models.BooleanField(default=False)),
                ("tree2", models.BooleanField(default=False)),
                ("hand2", models.BooleanField(default=False)),
                ("wind2", models.BooleanField(default=False)),
                ("knee2", models.BooleanField(default=False)),
                ("WL_trial2_score", models.IntegerField(default=0)),
                ("stone3", models.BooleanField(default=False)),
                ("ear3", models.BooleanField(default=False)),
                ("neck3", models.BooleanField(default=False)),
                ("cloud3", models.BooleanField(default=False)),
                ("foot3", models.BooleanField(default=False)),
                ("seed3", models.BooleanField(default=False)),
                ("tongue3", models.BooleanField(default=False)),
                ("sand3", models.BooleanField(default=False)),
                ("fire3", models.BooleanField(default=False)),
                ("nose3", models.BooleanField(default=False)),
                ("tree3", models.BooleanField(default=False)),
                ("hand3", models.BooleanField(default=False)),
                ("wind3", models.BooleanField(default=False)),
                ("knee3", models.BooleanField(default=False)),
                ("WL_trial3_score", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Protocols_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
