# Generated by Django 4.1.4 on 2023-02-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="words_memory_subtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stone1", models.BooleanField(default=False)),
                ("ear1", models.BooleanField(default=False)),
                ("neck1", models.BooleanField(default=False)),
                ("cloud1", models.BooleanField(default=False)),
                ("foot1", models.BooleanField(default=False)),
                ("seed1", models.BooleanField(default=False)),
                ("tongue1", models.BooleanField(default=False)),
                ("sand1", models.BooleanField(default=False)),
                ("fire1", models.BooleanField(default=False)),
                ("nose1", models.BooleanField(default=False)),
                ("tree1", models.BooleanField(default=False)),
                ("hand1", models.BooleanField(default=False)),
                ("wind1", models.BooleanField(default=False)),
                ("knee1", models.BooleanField(default=False)),
                ("WL_trial1", models.IntegerField()),
            ],
        ),
    ]
