# Generated by Django 4.1.4 on 2023-02-05 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("words", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                (
                    "word_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="muns_app.wordlist",
                    ),
                ),
            ],
        ),
    ]
