# Generated by Django 4.1.4 on 2023-02-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muns_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsLearningSubtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone1', models.BooleanField(default=False)),
                ('ear1', models.BooleanField(default=False)),
                ('neck1', models.BooleanField(default=False)),
                ('cloud1', models.BooleanField(default=False)),
                ('foot1', models.BooleanField(default=False)),
                ('seed1', models.BooleanField(default=False)),
                ('tongue1', models.BooleanField(default=False)),
                ('sand1', models.BooleanField(default=False)),
                ('fire1', models.BooleanField(default=False)),
                ('nose1', models.BooleanField(default=False)),
                ('tree1', models.BooleanField(default=False)),
                ('hand1', models.BooleanField(default=False)),
                ('wind1', models.BooleanField(default=False)),
                ('knee1', models.BooleanField(default=False)),
                ('WL_trial1_score', models.IntegerField(default=0)),
                ('stone2', models.BooleanField(default=False)),
                ('ear2', models.BooleanField(default=False)),
                ('neck2', models.BooleanField(default=False)),
                ('cloud2', models.BooleanField(default=False)),
                ('foot2', models.BooleanField(default=False)),
                ('seed2', models.BooleanField(default=False)),
                ('tongue2', models.BooleanField(default=False)),
                ('sand2', models.BooleanField(default=False)),
                ('fire2', models.BooleanField(default=False)),
                ('nose2', models.BooleanField(default=False)),
                ('tree2', models.BooleanField(default=False)),
                ('hand2', models.BooleanField(default=False)),
                ('wind2', models.BooleanField(default=False)),
                ('knee2', models.BooleanField(default=False)),
                ('WL_trial2_score', models.IntegerField(default=0)),
                ('stone3', models.BooleanField(default=False)),
                ('ear3', models.BooleanField(default=False)),
                ('neck3', models.BooleanField(default=False)),
                ('cloud3', models.BooleanField(default=False)),
                ('foot3', models.BooleanField(default=False)),
                ('seed3', models.BooleanField(default=False)),
                ('tongue3', models.BooleanField(default=False)),
                ('sand3', models.BooleanField(default=False)),
                ('fire3', models.BooleanField(default=False)),
                ('nose3', models.BooleanField(default=False)),
                ('tree3', models.BooleanField(default=False)),
                ('hand3', models.BooleanField(default=False)),
                ('wind3', models.BooleanField(default=False)),
                ('knee3', models.BooleanField(default=False)),
                ('WL_trial3_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='words_memory_subtest',
        ),
    ]
